### ISSUE TITLE
Moving TODOs to Issues

### ISSUE THREAD

**Issue by TheVulch** [CSClub-at-OSU/Website2.0#1]
@ksliker89 @siphayne What do you think?

Seems like the perfect switch - we can assign people, add milestones, labels, etc.

**Comment by siphayne** [comment]
Sounds good to me. You're the man when it comes to this while Github thing.

**Comment by TheVulch** [comment]
Sounds good! If sliker's good for it too, I'll start the conversion.

**Comment by ksliker89** [comment]
Convert away! I'm good with it.

**Comment by TheVulch** [comment]
Sweet.
